language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk6
  - oraclejdk7

before_install:
  - git submodule update --init --recursive

install: mvn install -DskipTests=true -Dgpg.skip=true

after_script: mvn cobertura:cobertura coveralls:cobertura

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always
